import type { Metadata } from 'next'
import './globals.scss'
import MainHeader from './components/main-header/main-header'
import { ReactNode } from 'react'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: ReactNode }) => {
    return (
        <html lang="en">
            <body>
                <MainHeader />
                {children}
            </body>
        </html>
    )
}

export default RootLayout
